name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: build
    steps:
    - uses: actions/checkout@v2

    - name: Create build directory
      run: mkdir -p build
      working-directory: .

    - name: Configure
      run: cmake -DCMAKE_TOOLCHAIN_FILE=${ANDROID_SDK_ROOT}/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_PLATFORM=16 -DANDROID_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Debug ..

    - name: Build
      run: cmake --build . --parallel

    - name: Test
      run: ctest --output-on-failure
